//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStockBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringType
    {
        public RecurringType()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int RecurringTypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
