//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStockBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string UserID { get; set; }
        public int TransactionTypeID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> Shares { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual TransactionType TransactionType { get; set; }
        public virtual User User { get; set; }
    }
}
